import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Debug: visa om env-variabler finns (visar inte nyckel i klartext)
console.log("DEBUG: Supabase env - URL exists:", !!SUPABASE_URL, "ANON exists:", !!SUPABASE_ANON_KEY);

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// --- NEW VALUATION FUNCTIONS ---

/**
 * Uploads multiple image files to the 'images' storage bucket.
 * @param files The array of File objects to upload.
 * @returns A promise that resolves to an array of public image URLs.
 */
export async function uploadImages(files: File[]): Promise<string[]> {
  const uploadPromises = files.map((file) => {
    // Create a unique file name to avoid collisions
    const fileName = `public/${Date.now()}-${file.name.replace(/\s/g, "_")}`;
    return supabase.storage.from("images").upload(fileName, file);
  });

  const uploadResults = await Promise.all(uploadPromises);

  const urls: string[] = [];
  for (const result of uploadResults) {
    if (result.error) {
      console.error("Error uploading image:", result.error);
      throw result.error;
    }
    const { data } = supabase.storage.from("images").getPublicUrl(result.data.path);
    urls.push(data.publicUrl);
  }

  return urls;
}

/**
 * Saves the valuation analysis and image URLs to the 'valuations' database table.
 * @param analysisResult The text generated by Gemini.
 * @param imageUrls The array of public URLs for the uploaded images.
 * @param customerId The ID of the customer creating the valuation.
 */
export async function saveValuation(
  analysisResult: string,
  imageUrls: string[],
  customerId: string
) {
  const { data, error } = await supabase
    .from("valuations")
    .insert([
      {
        analysis_result: analysisResult,
        image_urls: imageUrls,
        customer_id: customerId,
      },
    ])
    .select();

  if (error) {
    console.error("Error saving valuation:", error);
    throw error;
  }

  return data;
}

/**
 * Fetches all valuation records from the database, including customer info.
 * @returns A promise that resolves to an array of valuation objects.
 */
export async function getValuations() {
  // Hämta endast valuations direkt — undvik att selekta från auth.users här (orsakar PGRST100)
  const { data, error } = await supabase
    .from("valuations")
    .select("*")
    .order("created_at", { ascending: false });

  if (error) throw error;
  return data ?? [];
}

// --- EXISTING DATABASE TYPES ---

export interface Customer {
  id: string;
  email: string;
  name: string;
  phone?: string;
  address?: string;
  created_at: string;
  is_admin: boolean;
}

export interface ServiceType {
  id: string;
  name: string;
  description: string;
  base_price?: number;
  created_at: string;
}

export interface Subscription {
  id: string;
  name: string;
  provider: string;
  category: string;
  created_at: string;
}

export interface Case {
  id: string;
  customer_id: string;
  service_type_id: string;
  title: string;
  description: string;
  status: "pending" | "in_progress" | "completed" | "cancelled";
  priority: "low" | "medium" | "high";
  scheduled_date?: string;
  completion_date?: string;
  total_price?: number;
  address?: string;
  notes?: string;
  created_at: string;
  updated_at: string;
  // Relations
  customer?: Customer;
  service_type?: ServiceType;
}

export interface CaseSubscription {
  id: string;
  case_id: string;
  subscription_id: string;
  status: "active" | "cancelled" | "completed";
  cancellation_date?: string;
  notes?: string;
  created_at: string;
  // Relations
  subscription?: Subscription;
}

export interface ContactRequest {
  id: string;
  name: string;
  email: string;
  phone?: string;
  service_interest?: string;
  message: string;
  status: "new" | "contacted" | "quoted" | "converted" | "closed";
  admin_notes?: string;
  created_at: string;
  updated_at: string;
}

export interface CaseComment {
  id: string;
  case_id: string;
  author_id: string;
  author_type: "customer" | "admin";
  content: string;
  created_at: string;
  // Relations
  author?: Customer;
}

export interface StorageItem {
  id: string;
  case_id: string;
  item_name: string;
  description?: string;
  quantity: number;
  storage_location?: string;
  status: "stored" | "retrieved" | "disposed";
  stored_date: string;
  retrieved_date?: string;
  monthly_cost?: number;
  created_at: string;
}