import { createClient, type SupabaseClient } from '@supabase/supabase-js';

// IMPORTANT: Replace with your Supabase project's URL and Anon Key.
// In a real application, these should be stored securely in environment variables.
const supabaseUrl = 'YOUR_SUPABASE_PROJECT_URL';
const supabaseAnonKey = 'YOUR_SUPABASE_ANON_KEY';

// Conditionally initialize the Supabase client to avoid crashing the app
// if the credentials are still placeholders.
let supabase: SupabaseClient | null = null;

const areCredentialsValid = supabaseUrl && supabaseAnonKey && !supabaseUrl.includes('YOUR_SUPABASE_PROJECT_URL');

if (areCredentialsValid) {
  try {
    supabase = createClient(supabaseUrl, supabaseAnonKey);
  } catch (error) {
    console.error("Failed to initialize Supabase client:", error);
    // Let the app continue running, but saving will be disabled.
  }
} else {
  console.warn("Supabase credentials are not configured in 'services/supabaseService.ts'. Saving functionality is disabled.");
}


/**
 * Checks if Supabase is properly configured and initialized.
 * @throws {Error} If the Supabase client is not available.
 */
function checkSupabaseIsConfigured() {
    if (!supabase) {
        throw new Error("Supabase is not configured. Please add your project URL and anon key in services/supabaseService.ts to enable saving.");
    }
}

/**
 * Uploads multiple image files to the 'item_images' storage bucket.
 * @param files The array of File objects to upload.
 * @returns A promise that resolves to an array of public image URLs.
 */
export async function uploadImages(files: File[]): Promise<string[]> {
  checkSupabaseIsConfigured();

  const uploadPromises = files.map(file => {
    // Create a unique file name to avoid collisions
    const fileName = `public/${Date.now()}-${file.name.replace(/\s/g, '_')}`;
    return supabase!.storage.from('item_images').upload(fileName, file);
  });

  const uploadResults = await Promise.all(uploadPromises);

  const urls: string[] = [];
  for (const result of uploadResults) {
    if (result.error) {
      console.error('Error uploading image:', result.error);
      throw result.error;
    }
    const { data } = supabase!.storage.from('item_images').getPublicUrl(result.data.path);
    urls.push(data.publicUrl);
  }

  return urls;
}

/**
 * Saves the valuation analysis and image URLs to the 'valuations' database table.
 * @param analysisResult The text generated by Gemini.
 * @param imageUrls The array of public URLs for the uploaded images.
 */
export async function saveValuation(analysisResult: string, imageUrls: string[]) {
  checkSupabaseIsConfigured();

  const { data, error } = await supabase!
    .from('valuations')
    .insert([
      { analysis_result: analysisResult, image_urls: imageUrls },
    ])
    .select();

  if (error) {
    console.error('Error saving valuation:', error);
    throw error;
  }
  
  return data;
}
