-- Fix key receipts storage RLS policies to match actual file paths
-- The customer select/insert policies were checking for wrong path pattern
-- Generated by buildCustomerPath as: customers/{customerId}/key-receipts/{receiptId}/signature.png
-- But policies expected: key-receipts/{uuid}/signature.png

begin;

-- Drop old policies with incorrect path patterns
drop policy if exists key_receipts_customer_select on storage.objects;
drop policy if exists key_receipts_customer_insert on storage.objects;

-- Recreate with correct path patterns
create policy key_receipts_customer_select
  on storage.objects for select
  using (
    bucket_id = 'key-receipts'
    and name ~ '^customers/[0-9a-fA-F-]{36}/key-receipts/[0-9a-fA-F-]{36}/signature\\.png$'
    and exists (
      select 1
      from public.key_receipts kr
      where kr.id = split_part(name,'/',4)::uuid
        and kr.customer_id = auth.uid()
    )
  );

create policy key_receipts_customer_insert
  on storage.objects for insert
  with check (
    bucket_id = 'key-receipts'
    and name ~ '^customers/[0-9a-fA-F-]{36}/key-receipts/[0-9a-fA-F-]{36}/signature\\.png$'
    and exists (
      select 1
      from public.key_receipts kr
      where kr.id = split_part(name,'/',4)::uuid
        and kr.customer_id = auth.uid()
    )
  );

commit;
