import { createClient } from '@supabase/supabase-js'

// CORRECTED: Reverted to using import.meta.env, which is the standard way Vite
// exposes environment variables to the client-side code. Using process.env
// caused a runtime error because it's not available in the browser.
// FIX: Cast `import.meta` to `any` to prevent TypeScript errors when `vite/client` types are not available.
const supabaseUrl = (import.meta as any).env.VITE_SUPABASE_URL;
const supabaseAnonKey = (import.meta as any).env.VITE_SUPABASE_ANON_KEY;


if (!supabaseUrl || !supabaseAnonKey) {
  // Provide a more helpful error message for the user.
  throw new Error("Supabase URL and Anon Key are required. Make sure you have a .env file with VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY variables set.");
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export const signIn = async (email: string, password: string) => {
  const { data, error } = await supabase.auth.signInWithPassword({
    email,
    password
  });
  return { data, error };
};


// --- NEW VALUATION FUNCTIONS ---

/**
 * Uploads multiple image files to the 'images' storage bucket.
 * @param files The array of File objects to upload.
 * @returns A promise that resolves to an array of public image URLs.
 */
export async function uploadImages(files: File[]): Promise<string[]> {
  const uploadPromises = files.map(file => {
    // Create a unique file name to avoid collisions
    const fileName = `public/${Date.now()}-${file.name.replace(/\s/g, '_')}`;
    return supabase.storage.from('images').upload(fileName, file);
  });

  const uploadResults = await Promise.all(uploadPromises);

  const urls: string[] = [];
  for (const result of uploadResults) {
    if (result.error) {
      console.error('Error uploading image:', result.error);
      throw result.error;
    }
    const { data } = supabase.storage.from('images').getPublicUrl(result.data.path);
    urls.push(data.publicUrl);
  }

  return urls;
}

/**
 * Saves the valuation analysis and image URLs to the 'valuations' database table.
 * @param analysisResult The text generated by Gemini.
 * @param imageUrls The array of public URLs for the uploaded images.
 * @param customerId The ID of the customer creating the valuation.
 */
export async function saveValuation(analysisResult: string, imageUrls: string[], customerId: string) {
  const { data, error } = await supabase
    .from('valuations')
    .insert([
      { 
        analysis_result: analysisResult, 
        image_urls: imageUrls,
        customer_id: customerId 
      },
    ])
    .select();

  if (error) {
    console.error('Error saving valuation:', error);
    throw error;
  }
  
  return data;
}

/**
 * Fetches all valuation records from the database, including customer info.
 * @returns A promise that resolves to an array of valuation objects.
 */
export async function getValuations() {
  // 1) hämta valuations utan relation-join
  const { data: vals, error: vErr } = await supabase
    .from("valuations")
    .select("*")
    .order("created_at", { ascending: false });

  if (vErr) throw vErr;
  const valArr = vals ?? [];

  // 2) samla customer_ids och hämta customers separat
  const customerIds = Array.from(new Set(valArr.map((v: any) => v.customer_id).filter(Boolean)));
  if (customerIds.length === 0) {
    return valArr.map((v: any) => ({ ...v, customer: null }));
  }

  const { data: customers, error: cErr } = await supabase
    .from("customers")
    .select("id,name,email")
    .in("id", customerIds);

  if (cErr) {
    console.warn("Could not fetch customers:", cErr);
    // return valuations without customer info
    return valArr.map((v: any) => ({ ...v, customer: null }));
  }

  const custMap = new Map((customers || []).map((c: any) => [c.id, c]));
  return valArr.map((v: any) => ({ ...v, customer: custMap.get(v.customer_id) ?? null }));
}


// --- EXISTING DATABASE TYPES ---

export interface Customer {
  id: string
  email: string
  name: string
  phone?: string
  address?: string
  created_at: string
  is_admin: boolean
}

export interface ServiceType {
  id: string
  name: string
  description: string
  base_price?: number
  created_at: string
}

export interface Subscription {
  id: string
  name: string
  provider: string
  category: string
  created_at: string
}

export interface Case {
  id: string
  customer_id: string
  service_type_id: string
  title: string
  description: string
  status: 'pending' | 'in_progress' | 'completed' | 'cancelled'
  priority: 'low' | 'medium' | 'high'
  scheduled_date?: string
  completion_date?: string
  total_price?: number
  address?: string
  notes?: string
  created_at: string
  updated_at: string
  // Relations
  customer?: Customer
  service_type?: ServiceType
}

export interface CaseSubscription {
  id: string
  case_id: string
  subscription_id: string
  status: 'active' | 'cancelled' | 'completed'
  cancellation_date?: string
  notes?: string
  created_at: string
  // Relations
  subscription?: Subscription
}

export interface ContactRequest {
  id: string
  name: string
  email: string
  phone?: string
  service_interest?: string
  message: string
  status: 'new' | 'contacted' | 'quoted' | 'converted' | 'closed'
  admin_notes?: string
  created_at: string
  updated_at: string
}

export interface CaseComment {
  id: string
  case_id: string
  author_id: string
  author_type: 'customer' | 'admin'
  content: string
  created_at: string
  // Relations
  author?: Customer
}

export interface StorageItem {
  id: string
  case_id: string
  item_name: string
  description?: string
  quantity: number
  storage_location?: string
  status: 'stored' | 'retrieved' | 'disposed'
  stored_date: string
  retrieved_date?: string
  monthly_cost?: number
  created_at: string
}